/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as PlatformAuditRouteImport } from './routes/_platform/audit'
import { Route as PlatformBillingRouteImport } from './routes/_platform/billing'
import { Route as PlatformDashboardRouteImport } from './routes/_platform/dashboard'
import { Route as PlatformErrorsRouteImport } from './routes/_platform/errors'
import { Route as PlatformPaymentsRouteImport } from './routes/_platform/payments'
import { Route as PlatformPermissionsRouteImport } from './routes/_platform/permissions'
import { Route as PlatformPlansRouteImport } from './routes/_platform/plans'
import { Route as PlatformPlatformAdminsRouteImport } from './routes/_platform/platform-admins'
import { Route as PlatformSettingsRouteImport } from './routes/_platform/settings'
import { Route as PlatformSubscriptionsRouteImport } from './routes/_platform/subscriptions'
import { Route as PlatformSystemRouteImport } from './routes/_platform/system'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PlatformAnalyticsGrowthRouteImport } from './routes/_platform/analytics/growth'
import { Route as PlatformAnalyticsOrdersRouteImport } from './routes/_platform/analytics/orders'
import { Route as PlatformAnalyticsRevenueRouteImport } from './routes/_platform/analytics/revenue'
import { Route as PlatformOrganizationsIndexRouteImport } from './routes/_platform/organizations/index'
import { Route as PlatformOrganizationsOrganizationIdRouteImport } from './routes/_platform/organizations/$organizationId'
import { Route as PlatformOrganizationsActiveRouteImport } from './routes/_platform/organizations/active'
import { Route as PlatformOrganizationsPendingRouteImport } from './routes/_platform/organizations/pending'
import { Route as PlatformOrganizationsSuspendedRouteImport } from './routes/_platform/organizations/suspended'
import { Route as PlatformOrganizationsTrialRouteImport } from './routes/_platform/organizations/trial'
import { Route as PlatformUsageIndexRouteImport } from './routes/_platform/usage/index'
import { Route as PlatformUsageFeaturesRouteImport } from './routes/_platform/usage/features'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformBillingRoute = PlatformBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformErrorsRoute = PlatformErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPaymentsRoute = PlatformPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPermissionsRoute = PlatformPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlatformAdminsRoute = PlatformPlatformAdminsRouteImport.update({
  id: '/platform-admins',
  path: '/platform-admins',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSubscriptionsRoute = PlatformSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSystemRoute = PlatformSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => PlatformRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAnalyticsGrowthRoute = PlatformAnalyticsGrowthRouteImport.update({
  id: '/analytics/growth',
  path: '/analytics/growth',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAnalyticsOrdersRoute = PlatformAnalyticsOrdersRouteImport.update({
  id: '/analytics/orders',
  path: '/analytics/orders',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAnalyticsRevenueRoute =
  PlatformAnalyticsRevenueRouteImport.update({
    id: '/analytics/revenue',
    path: '/analytics/revenue',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformOrganizationsIndexRoute =
  PlatformOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformOrganizationsOrganizationIdRoute =
  PlatformOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformOrganizationsActiveRoute =
  PlatformOrganizationsActiveRouteImport.update({
    id: '/organizations/active',
    path: '/organizations/active',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformOrganizationsPendingRoute =
  PlatformOrganizationsPendingRouteImport.update({
    id: '/organizations/pending',
    path: '/organizations/pending',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformOrganizationsSuspendedRoute =
  PlatformOrganizationsSuspendedRouteImport.update({
    id: '/organizations/suspended',
    path: '/organizations/suspended',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformOrganizationsTrialRoute =
  PlatformOrganizationsTrialRouteImport.update({
    id: '/organizations/trial',
    path: '/organizations/trial',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformUsageIndexRoute = PlatformUsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformUsageFeaturesRoute = PlatformUsageFeaturesRouteImport.update({
  id: '/usage/features',
  path: '/usage/features',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof PlatformAuditRoute
  '/billing': typeof PlatformBillingRoute
  '/dashboard': typeof PlatformDashboardRoute
  '/errors': typeof PlatformErrorsRoute
  '/payments': typeof PlatformPaymentsRoute
  '/permissions': typeof PlatformPermissionsRoute
  '/plans': typeof PlatformPlansRoute
  '/platform-admins': typeof PlatformPlatformAdminsRoute
  '/settings': typeof PlatformSettingsRoute
  '/subscriptions': typeof PlatformSubscriptionsRoute
  '/system': typeof PlatformSystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/analytics/growth': typeof PlatformAnalyticsGrowthRoute
  '/analytics/orders': typeof PlatformAnalyticsOrdersRoute
  '/analytics/revenue': typeof PlatformAnalyticsRevenueRoute
  '/organizations/$organizationId': typeof PlatformOrganizationsOrganizationIdRoute
  '/organizations/active': typeof PlatformOrganizationsActiveRoute
  '/organizations/pending': typeof PlatformOrganizationsPendingRoute
  '/organizations/suspended': typeof PlatformOrganizationsSuspendedRoute
  '/organizations/trial': typeof PlatformOrganizationsTrialRoute
  '/usage/features': typeof PlatformUsageFeaturesRoute
  '/organizations/': typeof PlatformOrganizationsIndexRoute
  '/usage/': typeof PlatformUsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof PlatformAuditRoute
  '/billing': typeof PlatformBillingRoute
  '/dashboard': typeof PlatformDashboardRoute
  '/errors': typeof PlatformErrorsRoute
  '/payments': typeof PlatformPaymentsRoute
  '/permissions': typeof PlatformPermissionsRoute
  '/plans': typeof PlatformPlansRoute
  '/platform-admins': typeof PlatformPlatformAdminsRoute
  '/settings': typeof PlatformSettingsRoute
  '/subscriptions': typeof PlatformSubscriptionsRoute
  '/system': typeof PlatformSystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/analytics/growth': typeof PlatformAnalyticsGrowthRoute
  '/analytics/orders': typeof PlatformAnalyticsOrdersRoute
  '/analytics/revenue': typeof PlatformAnalyticsRevenueRoute
  '/organizations/$organizationId': typeof PlatformOrganizationsOrganizationIdRoute
  '/organizations/active': typeof PlatformOrganizationsActiveRoute
  '/organizations/pending': typeof PlatformOrganizationsPendingRoute
  '/organizations/suspended': typeof PlatformOrganizationsSuspendedRoute
  '/organizations/trial': typeof PlatformOrganizationsTrialRoute
  '/usage/features': typeof PlatformUsageFeaturesRoute
  '/organizations': typeof PlatformOrganizationsIndexRoute
  '/usage': typeof PlatformUsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_platform': typeof PlatformRouteWithChildren
  '/_platform/audit': typeof PlatformAuditRoute
  '/_platform/billing': typeof PlatformBillingRoute
  '/_platform/dashboard': typeof PlatformDashboardRoute
  '/_platform/errors': typeof PlatformErrorsRoute
  '/_platform/payments': typeof PlatformPaymentsRoute
  '/_platform/permissions': typeof PlatformPermissionsRoute
  '/_platform/plans': typeof PlatformPlansRoute
  '/_platform/platform-admins': typeof PlatformPlatformAdminsRoute
  '/_platform/settings': typeof PlatformSettingsRoute
  '/_platform/subscriptions': typeof PlatformSubscriptionsRoute
  '/_platform/system': typeof PlatformSystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/_platform/analytics/growth': typeof PlatformAnalyticsGrowthRoute
  '/_platform/analytics/orders': typeof PlatformAnalyticsOrdersRoute
  '/_platform/analytics/revenue': typeof PlatformAnalyticsRevenueRoute
  '/_platform/organizations/$organizationId': typeof PlatformOrganizationsOrganizationIdRoute
  '/_platform/organizations/active': typeof PlatformOrganizationsActiveRoute
  '/_platform/organizations/pending': typeof PlatformOrganizationsPendingRoute
  '/_platform/organizations/suspended': typeof PlatformOrganizationsSuspendedRoute
  '/_platform/organizations/trial': typeof PlatformOrganizationsTrialRoute
  '/_platform/usage/features': typeof PlatformUsageFeaturesRoute
  '/_platform/organizations/': typeof PlatformOrganizationsIndexRoute
  '/_platform/usage/': typeof PlatformUsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/errors'
    | '/payments'
    | '/permissions'
    | '/plans'
    | '/platform-admins'
    | '/settings'
    | '/subscriptions'
    | '/system'
    | '/auth/login'
    | '/analytics/growth'
    | '/analytics/orders'
    | '/analytics/revenue'
    | '/organizations/$organizationId'
    | '/organizations/active'
    | '/organizations/pending'
    | '/organizations/suspended'
    | '/organizations/trial'
    | '/usage/features'
    | '/organizations/'
    | '/usage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/errors'
    | '/payments'
    | '/permissions'
    | '/plans'
    | '/platform-admins'
    | '/settings'
    | '/subscriptions'
    | '/system'
    | '/auth/login'
    | '/analytics/growth'
    | '/analytics/orders'
    | '/analytics/revenue'
    | '/organizations/$organizationId'
    | '/organizations/active'
    | '/organizations/pending'
    | '/organizations/suspended'
    | '/organizations/trial'
    | '/usage/features'
    | '/organizations'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/_platform'
    | '/_platform/audit'
    | '/_platform/billing'
    | '/_platform/dashboard'
    | '/_platform/errors'
    | '/_platform/payments'
    | '/_platform/permissions'
    | '/_platform/plans'
    | '/_platform/platform-admins'
    | '/_platform/settings'
    | '/_platform/subscriptions'
    | '/_platform/system'
    | '/auth/login'
    | '/_platform/analytics/growth'
    | '/_platform/analytics/orders'
    | '/_platform/analytics/revenue'
    | '/_platform/organizations/$organizationId'
    | '/_platform/organizations/active'
    | '/_platform/organizations/pending'
    | '/_platform/organizations/suspended'
    | '/_platform/organizations/trial'
    | '/_platform/usage/features'
    | '/_platform/organizations/'
    | '/_platform/usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/audit': {
      id: '/_platform/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/billing': {
      id: '/_platform/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof PlatformBillingRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/dashboard': {
      id: '/_platform/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/errors': {
      id: '/_platform/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof PlatformErrorsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/payments': {
      id: '/_platform/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PlatformPaymentsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/permissions': {
      id: '/_platform/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PlatformPermissionsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/plans': {
      id: '/_platform/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/platform-admins': {
      id: '/_platform/platform-admins'
      path: '/platform-admins'
      fullPath: '/platform-admins'
      preLoaderRoute: typeof PlatformPlatformAdminsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/settings': {
      id: '/_platform/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/subscriptions': {
      id: '/_platform/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof PlatformSubscriptionsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/system': {
      id: '/_platform/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof PlatformSystemRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/analytics/growth': {
      id: '/_platform/analytics/growth'
      path: '/analytics/growth'
      fullPath: '/analytics/growth'
      preLoaderRoute: typeof PlatformAnalyticsGrowthRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/analytics/orders': {
      id: '/_platform/analytics/orders'
      path: '/analytics/orders'
      fullPath: '/analytics/orders'
      preLoaderRoute: typeof PlatformAnalyticsOrdersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/analytics/revenue': {
      id: '/_platform/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof PlatformAnalyticsRevenueRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/organizations/': {
      id: '/_platform/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof PlatformOrganizationsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/organizations/$organizationId': {
      id: '/_platform/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof PlatformOrganizationsOrganizationIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/organizations/active': {
      id: '/_platform/organizations/active'
      path: '/organizations/active'
      fullPath: '/organizations/active'
      preLoaderRoute: typeof PlatformOrganizationsActiveRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/organizations/pending': {
      id: '/_platform/organizations/pending'
      path: '/organizations/pending'
      fullPath: '/organizations/pending'
      preLoaderRoute: typeof PlatformOrganizationsPendingRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/organizations/suspended': {
      id: '/_platform/organizations/suspended'
      path: '/organizations/suspended'
      fullPath: '/organizations/suspended'
      preLoaderRoute: typeof PlatformOrganizationsSuspendedRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/organizations/trial': {
      id: '/_platform/organizations/trial'
      path: '/organizations/trial'
      fullPath: '/organizations/trial'
      preLoaderRoute: typeof PlatformOrganizationsTrialRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/usage/': {
      id: '/_platform/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof PlatformUsageIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/usage/features': {
      id: '/_platform/usage/features'
      path: '/usage/features'
      fullPath: '/usage/features'
      preLoaderRoute: typeof PlatformUsageFeaturesRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface PlatformRouteChildren {
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformBillingRoute: typeof PlatformBillingRoute
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformErrorsRoute: typeof PlatformErrorsRoute
  PlatformPaymentsRoute: typeof PlatformPaymentsRoute
  PlatformPermissionsRoute: typeof PlatformPermissionsRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformPlatformAdminsRoute: typeof PlatformPlatformAdminsRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformSubscriptionsRoute: typeof PlatformSubscriptionsRoute
  PlatformSystemRoute: typeof PlatformSystemRoute
  PlatformAnalyticsGrowthRoute: typeof PlatformAnalyticsGrowthRoute
  PlatformAnalyticsOrdersRoute: typeof PlatformAnalyticsOrdersRoute
  PlatformAnalyticsRevenueRoute: typeof PlatformAnalyticsRevenueRoute
  PlatformOrganizationsOrganizationIdRoute: typeof PlatformOrganizationsOrganizationIdRoute
  PlatformOrganizationsActiveRoute: typeof PlatformOrganizationsActiveRoute
  PlatformOrganizationsPendingRoute: typeof PlatformOrganizationsPendingRoute
  PlatformOrganizationsSuspendedRoute: typeof PlatformOrganizationsSuspendedRoute
  PlatformOrganizationsTrialRoute: typeof PlatformOrganizationsTrialRoute
  PlatformUsageFeaturesRoute: typeof PlatformUsageFeaturesRoute
  PlatformOrganizationsIndexRoute: typeof PlatformOrganizationsIndexRoute
  PlatformUsageIndexRoute: typeof PlatformUsageIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformBillingRoute: PlatformBillingRoute,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformErrorsRoute: PlatformErrorsRoute,
  PlatformPaymentsRoute: PlatformPaymentsRoute,
  PlatformPermissionsRoute: PlatformPermissionsRoute,
  PlatformPlansRoute: PlatformPlansRoute,
  PlatformPlatformAdminsRoute: PlatformPlatformAdminsRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformSubscriptionsRoute: PlatformSubscriptionsRoute,
  PlatformSystemRoute: PlatformSystemRoute,
  PlatformAnalyticsGrowthRoute: PlatformAnalyticsGrowthRoute,
  PlatformAnalyticsOrdersRoute: PlatformAnalyticsOrdersRoute,
  PlatformAnalyticsRevenueRoute: PlatformAnalyticsRevenueRoute,
  PlatformOrganizationsOrganizationIdRoute:
    PlatformOrganizationsOrganizationIdRoute,
  PlatformOrganizationsActiveRoute: PlatformOrganizationsActiveRoute,
  PlatformOrganizationsPendingRoute: PlatformOrganizationsPendingRoute,
  PlatformOrganizationsSuspendedRoute: PlatformOrganizationsSuspendedRoute,
  PlatformOrganizationsTrialRoute: PlatformOrganizationsTrialRoute,
  PlatformUsageFeaturesRoute: PlatformUsageFeaturesRoute,
  PlatformOrganizationsIndexRoute: PlatformOrganizationsIndexRoute,
  PlatformUsageIndexRoute: PlatformUsageIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformRoute: PlatformRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
